<?php
/**
 * THE TEST-SUITE OUTBOUND MAIL BLOCK — theme 1.19.386.
 * Workstream `CYCLE179-LD-TEST-MAIL-SUPPRESS`.
 * ============================================================================
 *
 * Included at the top of EVERY `tests/test-*.php`. Nothing this suite does can
 * hand a message to a transport while it is loaded.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * ⭐⭐⭐ THE DEFECT THIS CLOSES — OBSERVED IN A LIVE MAIL LOG, NOT ANTICIPATED
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * ⛔ On 2026-09-06 Andrew received SIX "Address not found" bounces. They were
 *    real mail, sent from `andrew@braveheartspublishing.com`, generated by this
 *    repository's own test suites.
 *
 * ⭐ VERIFIED IN THE LIVE FLUENTSMTP LOG ON STAGING (read-only over SSH,
 *    2026-09-06, `ugc_fsmpt_email_logs`), not read out of a report — rows
 *    41–46, `status = sent`:
 *
 *      41  2026-09-06 13:40:56  bhp-cycle168+optin-failed@example.com
 *      42  2026-09-06 13:40:57  bhp-cycle168+optin-flip@example.com
 *      43  2026-09-06 13:40:58  bhp-cycle168+optin-flip2@example.com
 *      44  2026-09-06 14:08:53  bhp-cycle168+optin-failed@example.com
 *      45  2026-09-06 14:08:54  bhp-cycle168+optin-flip@example.com
 *      46  2026-09-06 14:08:55  bhp-cycle168+optin-flip2@example.com
 *
 *    Subject on all six: **"Your payment did not go through."** The addresses
 *    are `tests/test-cycle168-checkout-optin.php`'s fixtures; the two clusters
 *    are two separate suite runs.
 *
 * ⭐ WHY IT STARTED ON 2026-09-06 AND NOT BEFORE. Nothing in the suites
 *    changed. STAGING changed: since 2026-09-05 it relays through Google's
 *    SMTP relay via FluentSMTP, so a `wp_mail()` that used to die quietly on a
 *    box with no working mailer now genuinely leaves the building. ⛔ Every
 *    test that creates an order or moves one between statuses became an
 *    outbound-mail event overnight.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * ⛔⛔ WHY `add_filter( 'pre_wp_mail', '__return_false' )` WAS NOT WRITTEN
 *     LITERALLY, AND WHY THE SEAM WAS VERIFIED AT SOURCE FIRST
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * `pre_wp_mail` is applied inside `wp_mail()`, and **`wp_mail()` is pluggable.**
 * On staging it is NOT WordPress's own — measured, not assumed:
 *
 *     ReflectionFunction( 'wp_mail' )->getFileName()
 *       => wp-content/plugins/fluent-smtp/fluent-smtp.php:48
 *
 * ⛔ A filter registered against a hook that the live implementation never
 *    applies is a SILENT NO-OP, and this codebase has already paid for exactly
 *    that once: see `inc/staging-mail-guard.php`'s header, where a guard hung
 *    on `woocommerce_email_init` looked correct, passed every unit assertion,
 *    and suppressed nothing while four real emails went out.
 *
 * ⭐ SO THE REPLACEMENT WAS READ ON THE SERVER BEFORE ANY CODE WAS WRITTEN.
 *    `fluent-smtp/app/Functions/helpers.php:290` (`fluentMailSend()`) applies
 *    `wp_mail` and then, verbatim:
 *
 *        $pre_wp_mail = apply_filters( 'pre_wp_mail', null, $atts );
 *        if ( null !== $pre_wp_mail ) {
 *            return $pre_wp_mail;
 *
 *    ⭐ It short-circuits BEFORE its own logger and before any transport, which
 *    is why a blocked send adds ZERO rows to `ugc_fsmpt_email_logs` rather than
 *    a row marked failed. Both live implementations therefore honour the seam.
 *
 * ⭐ IT RETURNS `true`, NOT `false`, AND THAT IS DELIBERATE. Returning `false`
 *    makes `wp_mail()` report failure, which fires `wp_mail_failed`, flips
 *    `WC_Email::send()`'s return value and would rewrite the meaning of every
 *    existing assertion that reads "the mail was accepted". The block is about
 *    the TRANSPORT, not about simulating a broken mailer. `true` = "accepted,
 *    and captured here instead of sent" — the same convention
 *    `tests/test-cycle167-retailer-funnel.php` already uses locally.
 *
 * ⛔ A SUITE THAT NEEDS TO ASSERT ON AN EMAIL MUST READ IT FROM THE CAPTURE,
 *    NOT SEND IT. `bhp_test_mail_log()` returns every attempted message with
 *    its `to`, `subject`, `message`, `headers` and `attachments` intact — which
 *    is strictly more than a suite could observe from a successful send.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * ⭐⭐ THE BLOCK PROVES ITSELF AT INCLUDE TIME. IT DOES NOT ASSUME.
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Three checks run below, in ascending strength, and a failure of the last two
 * ABORTS THE SUITE (`exit( 1 )`) rather than letting it run unprotected:
 *
 *   1. the callback is registered on `pre_wp_mail`;
 *   2. `apply_filters( 'pre_wp_mail', … )` short-circuits and records — this
 *      exercises the contract with ZERO possibility of a send;
 *   3. a real `wp_mail()` call to an RFC 2606 `.invalid` recipient is captured
 *      and NOT transported — the only check that proves the WHOLE chain
 *      through whatever pluggable implementation is live.
 *
 * ⚠️ Check 3 is a real `wp_mail()` call and is stated as such rather than
 *    hidden. It is safe in three independent ways: check 2 has already proved
 *    the short-circuit fires; the recipient is under `.invalid`, a reserved TLD
 *    that can never resolve to a mailbox; and if it were somehow to escape, the
 *    capture count would not move, the suite would abort loudly, and the
 *    attempt would appear in the FluentSMTP log where this desk is counting
 *    rows anyway. ⛔ An unproven guard is the more expensive failure — that is
 *    the entire lesson of rows 41–46.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * ⛔ WHAT THIS FILE DOES NOT DO
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * - ⛔ It is NOT loaded by the theme. `functions.php` does not reference it and
 *   must not: it exists only for the duration of a `wp eval-file` suite run and
 *   has no effect on any web request, on either environment.
 * - ⛔ It writes NO option, product, order, price, coupon, stock, shipping, tax,
 *   payment or checkout setting, on any environment.
 * - ⛔ It does not touch production. Its scope is one PHP process.
 * - ⛔ It does not replace `inc/staging-mail-guard.php` or
 *   `inc/test-order-mail-guard.php`. Those two are theme-side and cover the
 *   paths a suite does not control; this one covers the suite itself. All three
 *   are deliberate belt and braces.
 *
 * @package Brave_Hearts
 */

defined( 'ABSPATH' ) || exit;

/*
 * ⛔ GUARDED TWICE. `require_once` already dedupes by realpath, but a suite run
 *    under `wp eval-file` is an eval'd scope and two spellings of the same path
 *    have bitten this repository before. The constant is the authority.
 */
if ( ! defined( 'BHP_TEST_MAIL_GUARD' ) ) {

	define( 'BHP_TEST_MAIL_GUARD', '1.19.386' );

	/*
	 * ⛔ THROUGH `$GLOBALS`, NOT A PLAIN LOCAL. Under `wp eval-file` this file's
	 *    top level is an eval'd scope, so `$captured = array();` would create a
	 *    LOCAL that `$GLOBALS['bhp_test_mail_captured']` never sees. Recorded in
	 *    `tests/test-staging-mail-guard.php` after it printed "25 passed,
	 *    failed" on a live run.
	 */
	$GLOBALS['bhp_test_mail_captured'] = array();

	if ( ! function_exists( 'bhp_test_mail_capture' ) ) {
		/**
		 * Capture an outbound message and stop it dead.
		 *
		 * @param null|bool $short_circuit WordPress's running answer. Always null here.
		 * @param array     $atts          Compacted `wp_mail()` arguments.
		 * @return bool TRUE — "accepted, and captured instead of sent".
		 */
		function bhp_test_mail_capture( $short_circuit, $atts = array() ) {
			unset( $short_circuit );

			$entry = is_array( $atts ) ? $atts : array();
			$entry['captured_at'] = time();

			$GLOBALS['bhp_test_mail_captured'][] = $entry;

			return true;
		}
	}

	if ( ! function_exists( 'bhp_test_mail_log' ) ) {
		/**
		 * Every message this run tried to send, in order.
		 *
		 * @return array[] Each entry carries to/subject/message/headers/attachments.
		 */
		function bhp_test_mail_log() {
			return isset( $GLOBALS['bhp_test_mail_captured'] ) && is_array( $GLOBALS['bhp_test_mail_captured'] )
				? $GLOBALS['bhp_test_mail_captured']
				: array();
		}
	}

	if ( ! function_exists( 'bhp_test_mail_count' ) ) {
		/**
		 * How many messages were blocked so far.
		 *
		 * @return int
		 */
		function bhp_test_mail_count() {
			return count( bhp_test_mail_log() );
		}
	}

	if ( ! function_exists( 'bhp_test_mail_clear' ) ) {
		/**
		 * Reset the capture so a probe reads only its own traffic.
		 *
		 * @return void
		 */
		function bhp_test_mail_clear() {
			$GLOBALS['bhp_test_mail_captured'] = array();
		}
	}

	if ( ! function_exists( 'bhp_test_mail_last' ) ) {
		/**
		 * The most recently blocked message, or null.
		 *
		 * @return array|null
		 */
		function bhp_test_mail_last() {
			$log = bhp_test_mail_log();
			return $log ? $log[ count( $log ) - 1 ] : null;
		}
	}

	if ( ! function_exists( 'bhp_test_mail_to_string' ) ) {
		/**
		 * Flatten one captured entry's recipients to a comparable string.
		 *
		 * @param array $entry A `bhp_test_mail_log()` entry.
		 * @return string
		 */
		function bhp_test_mail_to_string( $entry ) {
			if ( ! is_array( $entry ) || ! isset( $entry['to'] ) ) {
				return '';
			}
			return is_array( $entry['to'] ) ? implode( ',', $entry['to'] ) : (string) $entry['to'];
		}
	}

	if ( ! function_exists( 'bhp_test_mail_find' ) ) {
		/**
		 * Blocked messages whose recipient list contains a needle.
		 *
		 * ⭐ The seam a suite should use instead of sending: assert on what was
		 *    ATTEMPTED, which is strictly more observable than a send.
		 *
		 * @param string $needle Substring to look for in the recipients.
		 * @return array[]
		 */
		function bhp_test_mail_find( $needle ) {
			$hits = array();
			foreach ( bhp_test_mail_log() as $entry ) {
				if ( '' !== (string) $needle && false !== stripos( bhp_test_mail_to_string( $entry ), (string) $needle ) ) {
					$hits[] = $entry;
				}
			}
			return $hits;
		}
	}

	add_filter( 'pre_wp_mail', 'bhp_test_mail_capture', PHP_INT_MAX, 2 );

	/* ═══════════════════════════════════════════════════════════════════════
	 * SELF-VERIFICATION — see this file's header for why all three run.
	 * ═══════════════════════════════════════════════════════════════════════ */

	/* 1 · registered at all. */
	if ( false === has_filter( 'pre_wp_mail', 'bhp_test_mail_capture' ) ) {
		echo "\n⛔ FATAL: the test mail block could not register on `pre_wp_mail`. SUITE ABORTED — no test runs unprotected.\n";
		exit( 1 );
	}

	/* 2 · the contract short-circuits, with no possibility of a send. */
	$bhp_tmg_before = bhp_test_mail_count();
	$bhp_tmg_answer = apply_filters(
		'pre_wp_mail',
		null,
		array(
			'to'          => 'contract-probe@bhp-mail-guard.invalid',
			'subject'     => 'BHP test mail block — contract probe',
			'message'     => 'Not sent. Not sendable.',
			'headers'     => '',
			'attachments' => array(),
		)
	);
	if ( true !== $bhp_tmg_answer || bhp_test_mail_count() !== $bhp_tmg_before + 1 ) {
		echo "\n⛔ FATAL: `pre_wp_mail` did not short-circuit to the capture. SUITE ABORTED — no test runs unprotected.\n";
		exit( 1 );
	}

	/*
	 * 3 · the WHOLE chain, through whatever pluggable `wp_mail()` is live.
	 *
	 * ⛔ THIS IS THE ONLY CHECK THAT CAN CATCH A REPLACED `wp_mail()` THAT
	 *    NEVER APPLIES THE FILTER — the exact silent no-op described in the
	 *    header. Check 2 has already proved the short-circuit, and the
	 *    recipient is under `.invalid` (RFC 2606), which can never resolve.
	 */
	$bhp_tmg_before = bhp_test_mail_count();
	$bhp_tmg_sent   = wp_mail(
		'chain-probe@bhp-mail-guard.invalid',
		'BHP test mail block — chain probe',
		'Not sent. Not sendable.'
	);
	if ( bhp_test_mail_count() !== $bhp_tmg_before + 1 ) {
		echo "\n⛔⛔ FATAL: a real wp_mail() call was NOT intercepted — `wp_mail()` is defined in "
			. ( function_exists( 'wp_mail' ) ? ( new ReflectionFunction( 'wp_mail' ) )->getFileName() : 'nowhere' )
			. " and does not apply `pre_wp_mail`.\n"
			. "⛔ SUITE ABORTED. Mail from this suite would reach a real relay. Fix the block before running anything.\n";
		exit( 1 );
	}
	if ( true !== $bhp_tmg_sent ) {
		echo "\n⚠️  WARNING: the block intercepted the chain probe but wp_mail() returned a non-true value. Nothing was sent; assertions that read a send's return value may be affected.\n";
	}

	/*
	 * ⭐ The two probes are removed so a suite's own `bhp_test_mail_count()`
	 *    starts at zero and reads only its own traffic.
	 */
	bhp_test_mail_clear();
	unset( $bhp_tmg_before, $bhp_tmg_answer, $bhp_tmg_sent );

	echo "⛔ OUTBOUND MAIL BLOCKED for this suite (tests/bootstrap-mail-guard.php " . BHP_TEST_MAIL_GUARD . "; verified live, 3/3 checks). Captures: bhp_test_mail_log().\n";
}
